### ISSUE TITLE
AssertionError on call to findItems

### ISSUE THREAD

**Issue by superelchi** [OfficeDev/ews-java-api#193]
Hi,

I' trying to read Emails from an Office 365 account.
Code:
```
ExchangeService service = new ExchangeService();
ExchangeCredentials credentials = new WebCredentials("XXX@YYY.onmicrosoft.com", "ZZZ");
service.setCredentials(credentials);
URI uri = new URI("https://outlook.office365.com/EWS/Exchange.asmx");
service.setUrl(uri);
PropertySet itemPropertySet = new PropertySet(BasePropertySet.FirstClassProperties);
itemPropertySet.setRequestedBodyType(BodyType.Text);
ItemView view = new ItemView(100);
view.setPropertySet(itemPropertySet);
view.getOrderBy().add(ItemSchema.DateTimeReceived, SortDirection.Ascending);
FindItemsResults<Item> results = service.findItems(WellKnownFolderName.Inbox, view);
```
This throws:
```
Exception in thread "main" java.lang.AssertionError: [ExchangeServiceBase.SaveHttpResponseHeaders] expect no headers in the dictionary yet.
	at microsoft.exchange.webservices.data.EwsUtilities.EwsAssert(EwsUtilities.java:350)
	at microsoft.exchange.webservices.data.ExchangeServiceBase.saveHttpResponseHeaders(ExchangeServiceBase.java:787)
	at microsoft.exchange.webservices.data.ExchangeServiceBase.processHttpResponseHeaders(ExchangeServiceBase.java:778)
	at microsoft.exchange.webservices.data.ServiceRequestBase.traceResponse(ServiceRequestBase.java:325)
	at microsoft.exchange.webservices.data.SimpleServiceRequestBase.readResponse(SimpleServiceRequestBase.java:150)
	at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:47)
	at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:136)
	at microsoft.exchange.webservices.data.ExchangeService.findItems(ExchangeService.java:807)
	at microsoft.exchange.webservices.data.ExchangeService.findItems(ExchangeService.java:850)
	at microsoft.exchange.webservices.data.ExchangeService.findItems(ExchangeService.java:926)
	at EWSMailer.readMail(EWSMailer.java:25)
```

If this code is run in non-debug mode (no "-ea") everything works fine.

OS: Linux Mint 64 bit
SDK: 1.6.0_45

Any clues?
 
superelchi

**Comment by serious6** [comment]
running it without "-ea" will prevent java.lang.assertions from beeing checked. That´s why you dont see the error in that case.

**Comment by superelchi** [comment]
Yeah. Sure. Running without "-ea" works.
But what use is an assert() that is always thrown - I thought assert should help you debug your code. Not crash it. ;)

superelchi

**Comment by serious6** [comment]
you are right. Looking at the [code](https://github.com/OfficeDev/ews-java-api/blob/1bc57e806d9fd1308b81fbab59bdd8422f3083bd/src/main/java/microsoft/exchange/webservices/data/ExchangeServiceBase.java#L787) I think the provided assertion might be wrong because it just checks if httpResponseHeaders `this.httpResponseHeaders.size() == 0` and afterwards clears it. This makes no sense from my point of view. Maybe there are some other assumptions why the headers should be clear here?

**Comment by kentongray** [comment]
I've been using the "old" EWS java API for months and attempted to update to this one and ran into this error. Looking back we removed that code from the "old" version because it did not seem to have a purpose and would always break otherwise working code. I think it should definitely be removed as it causes difficulty... Pull request coming
