### ISSUE TITLE
Invalid XML Characters are not removed?

### ISSUE THREAD

**Issue by casulworks** [OfficeDev/ews-java-api#233]
Guys I noticed that invalid XML characters are not removed and this causes problems when you try to read emails with special characters that can not be in XML The Exchange does not strip them so the client must do it

When I try to read some emails I get the following problem:

The request failed. ParseError at [row, col]: [1.1475]
Message: Character Referece "&# at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:71)

I enabled the trace and saw the xml response that causes the problem, as stretch below:

	<t:Subject>Pendencia(s) COVSB600 - PV 1582 - CONVENIO 975300 - CASEBR&#x1A;S CAIXA ASSIS</t:Subject>

Within the subject it has a special character &#x1A which is invalid in XML.
It seems that requires some modifications in EwsXmlReader to deal with this problem.

Regards,
Lucas

**Comment by wilsonw** [comment]
The issue is really with Exchange server side that if your mail contains invalid XML characters EWS will just send it back. And the exception is raised from JDK's XMLStreamReaderImpl.

**Comment by casulworks** [comment]
I know that is a issue with Exchange, but i don't think that Microsoft Exchange team will change this. To me the api need enhance about that. I sort of solved the problem (not in the way I would like). Before creating implement factory (EwsXmlReader:initializeXmlReader) I remove these characters from the stream and create a a new stream cleaned.

**Comment by wilsonw** [comment]
Yeah if MS is not able to fix then we need to have a clean InputStream.

That's actually handled in their .Net managed API. And again EWS is not accepting request contains invalid XML characters.

**Comment by serious6** [comment]
maybe anyone of you guys can provide a PR?

**Comment by wilsonw** [comment]
While intercepting InputStream is a way that could be quite expensive when dealing with large XML response to filter out things like &#1A;

Interestingly I noticed most these characters are actually Valid in XML1.1. But just that EWS returning with <?xml version="1.0" encoding="utf-8"?> it's not using XML11 scanner.

I'm exploring if we can find a way to force EwsXmlReader to use XML11 instead.

**Comment by casulworks** [comment]
I tried to change the xml response to 1.1 version It ignorantly changing the 1.0 part to 1.1, but did not work (of course what I thinking?). Yeah I also think that large xml files could have performance impact by "opening the stream" and remove those characteres and creating a cleaned one. Why with the managed api this seems to be no problem? It's beacuse of native xml reader or they made some sort cleaning?

**Comment by wilsonw** [comment]
So, I got this resolved in a pretty much hacking way. I'm not so happy about this as basically you need to copy quite a few OpenJDK JAXP code inside so I didn't create any patch here.

Firstly, create a new Scanner by extending XMLNSDocumentScannerImpl and override isInvalid(...), I use XML11 validation here.

public class XMLNSDocumentScannerXML11CharValidateImpl extends XMLNSDocumentScannerImpl {
	@Override
	protected boolean isInvalid(int value) {
		return (XML11Char.isXML11Invalid(value));
	}
}

And in order to use this new class, you need to basically create a new XMLStreamReaderImpl to use the new scanner, and create a new XMLInputFactoryImpl to create StreamReader instance.

**Comment by pathikrit** [comment]
Probably covered by #353 but here is another stacktrace:

```
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[4,760]
Message: Character reference "&#
    at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
    at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
    at microsoft.exchange.webservices.data.core.ExchangeService.internalBindToItems(ExchangeService.java:1343)
    at microsoft.exchange.webservices.data.core.ExchangeService.bindToItems(ExchangeService.java:1360)
    at com.coatue.gandalf.services.exchange.AppointmentsSyncer$$anonfun$com$coatue$gandalf$services$exchange$AppointmentsSyncer$$autoAcceptHandler$1.apply(AppointmentsSyncer.scala:196)
    at scala.util.Try$.apply(Try.scala:161)
```

**Comment by pathikrit** [comment]
If email body contains U+FFFF, the API returns 500 Internal Server Error:

EwsRequest:
```xml
<Trace Tag="EwsRequest" Tid="8777" Time="2016-02-05 00:17:58Z">
    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
        <soap:Header>
            <t:RequestServerVersion Version="Exchange2010_SP2"></t:RequestServerVersion>
        </soap:Header>
        <soap:Body>
            <m:CreateItem MessageDisposition="SendAndSaveCopy">
                <m:SavedItemFolderId>
                    <t:DistinguishedFolderId Id="sentitems"></t:DistinguishedFolderId>
                </m:SavedItemFolderId>
                <m:Items>
                    <t:Message>
                        <t:Subject>Test</t:Subject>
                        <t:Body BodyType="HTML">Hello World</t:Body>
                        <t:ToRecipients>
                            <t:Mailbox>
                                <t:EmailAddress>pbhowmick@coatue.com</t:EmailAddress>
                            </t:Mailbox>
                        </t:ToRecipients>
                    </t:Message>
                </m:Items>
            </m:CreateItem>
        </soap:Body>
    </soap:Envelope>
</Trace>
```
EwsResponse :
```xml
<Trace Tag="EwsResponse" Tid="8777" Time="2016-02-05 00:17:58Z">
    <?xml version="1.0" encoding="utf-8"?>
    <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
        <s:Body>
            <s:Fault>
                <faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorSchemaValidation</faultcode>
                <faultstring xml:lang="en-US">The request failed schema validation: '&#xFFFF;', hexadecimal value 0xFFFF, is an invalid character. Line 1,
                    position 653.
                </faultstring>
                <detail>
                    <e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorSchemaValidation</e:ResponseCode>
                    <e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request failed schema validation.</e:Message>
                    <t:MessageXml xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
                        <t:LineNumber>1</t:LineNumber>
                        <t:LinePosition>653</t:LinePosition>
                        <t:Violation>'&#xFFFF;', hexadecimal value 0xFFFF, is an invalid character. Line 1, position 653.</t:Violation>
                    </t:MessageXml>
                </detail>
            </s:Fault>
        </s:Body>
    </s:Envelope>
</Trace>
```

This is what the Java API returns:
```
2016-02-05 00:17:58.669 UTC [error] application play-akka.actor.default-dispatcher-10 requestId=4
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (500)Internal Server Error
 at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147) ~[ews-java-api-2.0.jar:na]
 at microsoft.exchange.webservices.data.core.service.item.EmailMessage.sendAndSaveCopy(EmailMessage.java:300) ~[ews-java-api-2.0.jar:na]
```

Sanitization is handled by the .NET library and should also be handled by the Java library.

See MSDN docs: https://technet.microsoft.com/en-us/library/gg585107(v=exchg.80).aspx

**Comment by udobranco** [comment]
I bumped on this problem using ews-java-api-2.0.jar.

The way I fixed was to change my load. 

I was doing: 
service.loadPropertiesForItems(findResults,
						new PropertySet(BasePropertySet.**FirstClassProperties**, EmailMessageSchema.Attachments));

then changed to: 
service.loadPropertiesForItems(findResults,
						new PropertySet(BasePropertySet.**IdOnly**, EmailMessageSchema.Attachments));

**Comment by udobranco** [comment]
I came across this bug the other day and my solution was to lower the emails I was processing each time. I was loading 50 per run and this seemed to be more of remanish data error than an error on the xml so I started doing 10 emails per run and repet 10 5 runs and this stop happening.

**Comment by girishghoda57** [comment]
@codecrafting-io @serious6  Can anyone know how to generate this type of email? I mean with special characters.

**Comment by friedran-levi** [comment]
i managed to create a postman request which creates an email with the &#x1A; character in the subject. 
If someone stumbles on this the url and authentification has to be set manually. NTLM Authentication with correct credentials has to be used. Others may work but i didn't try and i don't know.  
[EWS-Share.postman_collection.txt](https://github.com/OfficeDev/ews-java-api/files/6976230/EWS-Share.postman_collection.txt)
You may have to change the file type ending with json to import it into your postman
