### ISSUE TITLE
Local name cannot be null

### ISSUE THREAD

**Issue by mibto** [OfficeDev/ews-java-api#265]
Hi there

I get following exception using 'com.microsoft.ews-java-api:ews-java-api:2.0-SNAPSHOT' and Java 8:

```Caused by: javax.xml.stream.XMLStreamException: Local name cannot be null
at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:619)
at microsoft.exchange.webservices.data.WSSecurityBasedCredentials.emitExtraSoapHeaderNamespaceAliases(WSSecurityBasedCredentials.java:153)```

Your function emitExtraSoapHeaderNamespaceAliases actually does really call the function writeAttribute with null for the localName parameter.

  ```@Override
  protected void emitExtraSoapHeaderNamespaceAliases(XMLStreamWriter writer)
      throws XMLStreamException {
    writer.writeAttribute(
        "xmlns",
        EwsUtilities.WSSecuritySecExtNamespacePrefix,
        null,
        EwsUtilities.WSSecuritySecExtNamespace);
    writer.writeAttribute(
        "xmlns",
        EwsUtilities.WSAddressingNamespacePrefix,
        null,
        EwsUtilities.WSAddressingNamespace);
  }

**Comment by serious6** [comment]
@mibto I made a PR with a possible fix for your problem. Maybe you can have a short test (since I currently don't have an integration test for it)?
