### ISSUE TITLE
TokenCredentials causes a ServiceRequestException

### ISSUE THREAD

**Issue by kyanskeem** [OfficeDev/ews-java-api#266]
When using TokenCredentials, I get the following error:

    microsoft.exchange.webservices.data.ServiceRequestException: The request failed. NamespaceURI cannot be null 
        at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:70) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:145) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ExchangeService.internalBindToItems(ExchangeService.java:1187) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ExchangeService.bindToItem(ExchangeService.java:1223) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ExchangeService.bindToItem(ExchangeService.java:1242) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.EmailMessage.bind(EmailMessage.java:71) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
    Caused by: javax.xml.stream.XMLStreamException: NamespaceURI cannot be null
        at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(Unknown Source) ~[na:1.7.0_67]
        at microsoft.exchange.webservices.data.WSSecurityBasedCredentials.emitExtraSoapHeaderNamespaceAliases(WSSecurityBasedCredentials.java:153) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ServiceRequestBase.writeToXml(ServiceRequestBase.java:206) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:731) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:690) ~[ews-java-api-2.0-SNAPSHOT.jar:na]
        at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:58) ~[ews-java-api-2.0-SNAPSHOT.jar:na]

My code looks like the following:

    ExchangeService exService = new ExchangeService(ExchangeVersion.Exchange2010_SP2);			
    ExchangeCredentials credentials = new TokenCredentials("TOKEN_VALUE");
    exService.setCredentials(credentials);
    exService.setUrl("EWS_SERVER_URL");	
    EmailMessage serverMessage = EmailMessage.bind(exService, new ItemId("ITEM_ID");

I tinkered with the offending class, WSSecurityBasedCredentials, and was able to get past this error, but the XML output ended up being garbled, with the header missing some tag names, as well as some escaped tags with &amp;lt; and &amp;gt; instead of &lt; and &gt; . .

In addtion, the word "null" gets prepended to the token when written to xml due to the concatenation of a null "timestamp" (see WSSecurityBasedCredentials line ~225. Initializing it to an empty string would fix this.

**Comment by serious6** [comment]
duplicates #265
