### ISSUE TITLE
Critical: NullPointerException when trying to send a message

### ISSUE THREAD

**Issue by tsoroka** [OfficeDev/ews-java-api#300]
1. Create EmailMessage
2. Execute message.send();
3. Result: NullPointerException
4. The reason: line 731 of 
```EwsUtilities: cls.isAssignableFrom(Number.class)``` return false if cls is ```Integer.class```

```java
StackTrace:

Caused by: java.lang.NullPointerException
	at microsoft.exchange.webservices.data.core.ExchangeServerInfo.parse(ExchangeServerInfo.java:80)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readSoapHeader(ServiceRequestBase.java:530)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:485)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:453)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:69)
	... 87 more
```

**Comment by serious6** [comment]
will be fixed with _ref. 293_

**Comment by serious6** [comment]
@tsoroka since the possible fix is merged. Plz report back if the error still exists. 
> closing this for now

**Comment by tsoroka** [comment]
@serious6 could you please let me know when this issue will be avaliable in a new shapshot build?

**Comment by serious6** [comment]
its included in the latest snapshot.
