### ISSUE TITLE
ExchangeServerInfo.parse() returns null, causes SimpleServiceRequestBase.internalExecute() to throw NPE

### ISSUE THREAD

**Issue by smakolski** [OfficeDev/ews-java-api#301]
So I've got some basic code:

``` java
ExchangeService service = new ExchangeService();
ExchangeCredentials credentials = new WebCredentials("username", "password", "domain");
service.setCredentials(credentials);
try {
    service.setUrl(new URI("https://example.com/EWS/Exchange.asmx"));
    ItemView view = new ItemView(10);
    FindItemsResults<Item> findResults = service.findItems(WellKnownFolderName.Inbox, view);
    for (Item item : findResults.getItems()) {
        System.out.println("id==========" + item.getId());
        System.out.println("sub==========" + item.getSubject());
    }
} catch (Exception e) {
    System.out.println("Exception: "+e.getLocalizedMessage());
    e.printStackTrace();
}
```

and it seems that service.findItems() throws a ServiceRequestExcepion: The request failed. null

```
microsoft.exchange.webservices.data.exception.ServiceRequestException: The request failed. null
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:80)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:984)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1027)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1103)
	at com.organization.project.component.EmailEWSConnector.main(EmailEWSConnector.java:7)
Caused by: java.lang.NullPointerException
	at microsoft.exchange.webservices.data.core.ExchangeServerInfo.parse(ExchangeServerInfo.java:80)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readSoapHeader(ServiceRequestBase.java:530)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:485)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:453)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:69)
	... 5 more
```

Taking a look at ExchangeServerInfo.parse(), it looks like it's failing to get server version information. Is there a way this condition could be handled gracefully? Is server version information really required for even a base level of functionality?

**Comment by smakolski** [comment]
To rule out a potentially misconfigured Exchange server, I tested this against https://outlook.office365.com/EWS/Exchange.asmx and got the same error with the same stack trace.

**Comment by smakolski** [comment]
This seems to be a duplicate of #300 and will be fixed with ref. #293

**Comment by serious6** [comment]
@smakolski since the possible fix is merged. Plz report back if the error still exists. 
> closing this for now
