### ISSUE TITLE
EmailMessageSchema.Body is unusable because it has a null name

### ISSUE THREAD

**Issue by srusso** [OfficeDev/ews-java-api#303]
ItemView view = new ItemView(pageSize, offset);
    view.setPropertySet(
         new PropertySet(
            ItemSchema.Subject,
            EmailMessageSchema.Body
         )
      );
      return this.exchangeService.findItems(WellKnownFolderName.Inbox, view);

This causes:
    Exception in thread "main" microsoft.exchange.webservices.data.exception.ServiceRequestException: The request failed. The property null can't be used in FindItem request.
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:80)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:984)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1028)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1103)
    ...
    ...

And in fact this
    System.out.println(EmailMessageSchema.Body.getName());
prints null. Is this the desired behaviour?

**Comment by Noblebrown** [comment]
This one brings us to another "What the heck is this??" moment. The name field in the PropertyDefintion class is not set via the constructor. It's set by calling ServiceObjectSchema.initializeSchemaPropertyNames(), which is a hideous abomination that was bound to cause problems thanks to the inexplicable use of reflection. I can't come up with a single plausible explanation as to why this mess was ever summoned into existence.

If this is a bug, then let's fix it and set the name property without the reflective horror.

**Comment by serious6** [comment]
hmm seems that `ServiceObjectSchema.allSchemaTypes.getMember()` is just an empty list when it is tried being iterated. The reason could be because [this](https://github.com/OfficeDev/ews-java-api/blob/e4bc4ac394d9772b0da0376dbca625ca4806bc2d/src/main/java/microsoft/exchange/webservices/data/core/service/schema/ServiceObjectSchema.java#L74) has been commented. A small test with the uncommented code (78 - 94) solves the problem and the name is set. 
@Noblebrown you are completely right with your statement. Unfortunately the requested change might be huge and the side effects are somehow incalculable.
So maybe we should also think of a short-termed solution here?

**Comment by michiwieland** [comment]
Is there any workaround available? I face the exact same problem with the complexType `MeetingMessageSchema.AssociatedAppointmentId`. I tried to fetch the AssociatedAppointmentId through MAPI-Properties (https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/mapi-properties), but unfortunately the field seems not to be available.
