### ISSUE TITLE
Autodiscover EWS url 

### ISSUE THREAD

**Issue by nshowkath** [OfficeDev/ews-java-api#325]
Hi ,

1)	To discover the EWS URL for O365 we have to use  Autodiscover option  
Is below  url is same for any organization or if every organization has different o365 url if they have online exchange 
            https://outlook.office365.com/EWS/Exchange.asmx

When we should we use Autodiscover option? 

We can determine url using below post operation or service.autodiscoverUrl(emailAddress);
2)	
POST /autodiscover/autodiscover.xml
https://mail.testdomain.com/Autodiscover/Autodiscover.xml
https://msdn.microsoft.com/en-us/library/office/ee332364(v=exchg.140).aspx 
<?xml version="1.0"?>
<Autodiscover
  xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006">
  <Request>
    <EMailAddress>user@contoso.com</EMailAddress>
    <AcceptableResponseSchema>
      http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a
    </AcceptableResponseSchema>
  </Request>
</Autodiscover
If everything is OK, then we'll get back a response
Or

service.autodiscoverUrl(emailAddress);

When should we use which option , In our application which deployed on cloud 
service.autodiscoverUrl(emailAddress) did not work , so we performed post operation to get url.

Could you share scenarios – When should we have to use Autodiscover application , On-premise Scenarios  and the applications deployed in cloud

**Comment by avromf** [comment]
Hi,

I work for an organization that uses Office365 and some of our clients do as well.
For all of us, the URL is https://outlook.office365.com/EWS/Exchange.asmx

The way I view the AutoDiscover feature is one of convenience. i.e. it can be used to auto configure so users don't have to themselves. However, EWS will work perfectly without this feature turned on.

In the application which I have integrated EWS with, I allow users to either manually enter the URL in our preferences or set it via the AutoDiscover feature. Then, all connections to EWS (i.e. the service object) are set using this URL. It is a lot slower to have AutoDiscover to do a lookup every single time. Also, this URL will rarely change.

**Comment by valenpo** [comment]
I trying to auth with Office365 via OAuth2 using ADAL4J library. 
I'm success get auth token for "https://outlook.office365.com", so next step is using EWS. 

```java
ExchangeService service = new ExchangeService();
					
					service.setCredentials(new OAuth2Credentials(authRes.getAccessToken()));
					service.setTraceEnabled(true);
					service.traceMessage(TraceFlags.EwsRequest, "office365");
					service.setImpersonatedUserId(new ImpersonatedUserId(ConnectingIdType.SmtpAddress, "jamie@archiva360.com"));
					service.setUrl(new URI("https://outlook.office365.com/ews/exchange.asmx"));


class OAuth2Credentials extends ExchangeCredentials {
	
	private String accessToken;

	public OAuth2Credentials(String accessToken) {
		Preconditions.checkNotNull(accessToken);
		this.accessToken = accessToken;
	}
	
	@Override
	public void prepareWebRequest(HttpWebRequest client)
			throws URISyntaxException {
		super.prepareWebRequest(client);
		if (client.getHeaders() != null) client.getHeaders().put("Authorization", "Bearer " + accessToken);
	}
}
```

and get error 
```
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request.
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalFindFolders(ExchangeService.java:372)
	at microsoft.exchange.webservices.data.core.ExchangeService.findFolders(ExchangeService.java:421)
	at microsoft.exchange.webservices.data.core.ExchangeService.findFolders(ExchangeService.java:456)
	at com.stimulus.archiva.connect.exchange.rest.OAuth2.main(OAuth2.java:88)
``` 

What is correct URL to get access Office365 ? 
Any clue?

**Comment by avromf** [comment]
@valenpo , you are using the correct EWS url for Office365.
Its https://outlook.office365.com/EWS/Exchange.asmx
Beyond that, I'm not sure what the problem is.

**Comment by yatinc1206** [comment]
Hi
I am using ews-java-api to connect outlook 2010
our exchange server service url is https://hostname/EWS/Exchange.asmx
I am trying to connect public folder root using following line of code

	public static void main(String[] args) {
		String serviceUrl = "";
		try {
			//Load Property
			Properties prop	= new Properties();
			prop.load(new FileInputStream("config.properties"));
			
			//Get exchange service object		
			ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);

			String mailId = prop.getProperty("mailId");
			String passWd = prop.getProperty("mailPwd");
			passWd = CryptBase64.decrypt(passWd);
			serviceUrl = prop.getProperty("serviceUrl");
			
			//System.out.println("mailId = "+mailId+"\t pwd = "+passWd+"\t serviceUrl = "+serviceUrl);
			
			//Set credentials
			ExchangeCredentials credentials = new WebCredentials( mailId, passWd);
			
			//Pass credentials to service
			service.setCredentials(credentials);
			
			//Set service Url
			service.setUrl(new URI(serviceUrl.trim()));
			//service.autodiscoverUrl(mailId);
			
			service.setTraceEnabled(true);
			
			FolderView view = new FolderView(1000);


			//Read Your own folder Items
			FolderId folderId = new FolderId(WellKnownFolderName.PublicFoldersRoot);
			
			ItemView itemview = new ItemView(1000);
			FindItemsResults<Item> findResults = service.findItems(folderId, itemview);

			for(Item f : findResults){
				System.out.println("Name : "+f.getSubject());
			}
		}catch(Exception e){
			e.printStackTrace();
		}
	}

but it is raising an exception as

microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: There are no public folder servers available.
	at microsoft.exchange.webservices.data.core.response.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:278)
	at microsoft.exchange.webservices.data.core.response.ServiceResponse.throwIfNecessary(ServiceResponse.java:267)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:165)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:985)
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1049)
	at com.wellmanage.fi.ReadFromPublicFolder.main(ReadFromPublicFolder.java:57)

what could be reason?

**Comment by yatinc1206** [comment]
@avromf
As you said not all exchnage server has public folder set up then what missing here if I am able to view public folders from outlook and I can send mail to that shared public folder also.
When I approached messaging team with above concern they are saying exchange has nothing to do with that issue.
So could you please tell which configurations need to be checked or set up to be made? So that I can convey the same to them.

Thanks

**Comment by davster** [comment]
The error you are getting from EWS suggests that you may be using the X-AnchorMailbox header incorrectly (or not using it).  That is basically a routing hint to the front end servers.  You are landing on a server in the wrong site.  Also, likely not related, but worth mentioning anyways, make sure you are getting the right scopes in your OAuth token:

https://msdn.microsoft.com/en-us/library/office/dn903761(v=exchg.150).aspx

**Comment by avromf** [comment]
@yatinc1206 My company's Exchange Server does not provide us with public folders. I just tested EWS now against our server by trying to access the root public folder and I got the exact same error.
From what I understand, shared folders are not the same as public folders. Maybe in your case it is actually a shared folder.

**Comment by yatinc1206** [comment]
@davster : what does mean by X-AnchorMailbox?
And I didn't get what you have commented.

@avromf :  Actually I am working on client remote desktop there we are implementing this.
what is difference between public folder and shared folder?
what about the view which am I getting in my mailbox under public folders. There I can see few number of folders. And what workaround you will suggest to get it executed.

**Comment by davster** [comment]
@yatinc1206 - your post above mentioned you receive:

_The request failed. Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request._

I am suggesting that you add an HTTP header to your request like this:
**X-AnchorMailbox: jamie@archiva360.com**

This is a routing hint for Exchange to get you to the right backend to start with instead of routing you incorrectly (long story) and causing a proxy which is where the above error is coming from.

**Comment by yatinc1206** [comment]
@davster : sorry but still not getting what you are trying to say.
And how it relate in my source code. Where I will have to use whatever you are saying?

**Comment by avromf** [comment]
@yatinc1206 
See this:
https://www.codetwo.com/admins-blog/office-365-shared-mailbox-vs-public-folders-whats-the-difference/
Or Microsoft's page:
https://technet.microsoft.com/en-us/library/jj983794(v=exchg.150).aspx

I do not know of any workaround you can implement. (Maybe consult with the IT people who are in charge of your Exchange Server so you will have a better idea of what you are dealing with.)

**Comment by avromf** [comment]
@davster I believe the post above that you are referring to was by @valenpo a while back.
I do not think it has anything to do with @yatinc1206 's issue.
