### ISSUE TITLE
Requires 3rd party jars. Can you document them?

### ISSUE THREAD

**Issue by douglasheld** [OfficeDev/ews-java-api#356]
Eclipse IDE for Java Developers, Version: Luna Service Release 2 (4.4.2)
Mac OS X 10.10.3
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

My project just does
ExchangeService service = new ExchangeService();

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/config/Lookup
	at Main.main(Main.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.http.config.Lookup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by serious6** [comment]
duplicates #355.

**Comment by serious6** [comment]
wiki section will be added once a stable release has been deployed.
