### ISSUE TITLE
[OOF] Can not access Out Of Facility data of another user : Access is denied. Check credentials and try again.

### ISSUE THREAD

**Issue by alibenmessaoud** [OfficeDev/ews-java-api#368]
I would like to get data about Out Of Facility. So I looked at the EWS API Docs and I written the code in Java.
When I tested using my credential and by passing my email address, the code works fine and the API returns what I need, but when I have sat the email of someone else, I got an Exception with this message : Access is denied. Check credentials and try again.
I would know if is there any other way to deal with this? I checked the EWS Docs and the associated methods are used to get only data for the identified user.

Here's the code : 

    ...
    OofSettings myOOF = new OofSettings();        
    OofSettings myOOFSettings = service.getUserOofSettings("un.ul@comp.com");
    OofExternalAudience myAllowedExternalAudience = myOOF.getAllowExternalOof();
    TimeWindow myOOFDuration = myOOF.getDuration();
     System.out.println(myOOFDuration.getStartTime());
     OofExternalAudience myExternalAudience = myOOF.getExternalAudience();
     OofReply myExternalReply = myOOF.getExternalReply();
     OofReply myInternalReply = myOOF.getInternalReply();
     OofState myOofState = myOOF.getState();

And the error full trace : 

	Exception in thread "main" microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: Access is denied. Check credentials and try again.
		at microsoft.exchange.webservices.data.core.response.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:278)
		at microsoft.exchange.webservices.data.core.response.ServiceResponse.throwIfNecessary(ServiceResponse.java:267)
		at microsoft.exchange.webservices.data.core.request.GetUserOofSettingsRequest.execute(GetUserOofSettingsRequest.java:154)
		at microsoft.exchange.webservices.data.core.ExchangeService.getUserOofSettings(ExchangeService.java:2592)
		at com.soprahr.hrlab.tests.OutOfOffice.main(OutOfOffice.java:39) 

Thanks in advance.

**Comment by RohitRSHARMA** [comment]
Hi Ali,

I am facing the same issue as well, please let me know if you found a solution for it.

Regards,
Rohit

**Comment by alibenmessaoud** [comment]
Hello,

I found a solution to deal with this issue. But it's not an official faeture of the API.
The trick is to use mail tips to send SOAP message to the Server.
And you have to put your mail and the destination mail to get the OOF automatic response and the the period of use.

This class and the code is in attachment, the trace below demonstrate a sample call and the response :

--- exec-maven-plugin:1.2.1:exec (default-cli) @ calnd.x01.ws ---
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="195" MinorBuildNumber="1" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetMailTipsResponse ResponseClass="Success" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><ResponseCode>NoError</ResponseCode><ResponseMessages><MailTipsResponseMessageType ResponseClass="Success"><ResponseCode>NoError</ResponseCode><m:MailTips xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><t:RecipientAddress xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><t:Name/><t:EmailAddress>philippe.royant@soprahr.com</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType></t:RecipientAddress><t:PendingMailTips xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"/><t:OutOfOffice xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><t:ReplyBody><t:Message>&lt;div&gt;&amp;#65279;&lt;style&gt;&#xD;
&lt;!--&#xD;
p.x_MsoNormal, li.x_MsoNormal, div.x_MsoNormal&#xD;
	{margin:0cm;&#xD;
	margin-bottom:.0001pt;&#xD;
	font-size:11.0pt;&#xD;
	font-family:"Calibri","sans-serif"}&#xD;
span.x_MsoHyperlink&#xD;
	{color:blue;&#xD;
	text-decoration:underline}&#xD;
span.x_MsoHyperlinkFollowed&#xD;
	{color:purple;&#xD;
	text-decoration:underline}&#xD;
span.x_EmailStyle17&#xD;
	{font-family:"Calibri","sans-serif"}&#xD;
.x_MsoChpDefault&#xD;
	{font-family:"Calibri","sans-serif"}&#xD;
div.x_WordSection1&#xD;
	{}&#xD;
--&gt;&#xD;
&lt;/style&gt;&#xD;
&lt;div class="x_WordSection1"&gt;&#xD;
&lt;p class="x_MsoNormal" style="text-autospace:none"&gt;Bonjour,&lt;br&gt;&#xD;
Je ne suis actuellement pas Ã  mon poste de travail.&lt;br&gt;&#xD;
Je vous rÃ©pondrais Ã  mon retour, le lundi 10 aoÃ»t 2015.&lt;br&gt;&#xD;
&lt;br&gt;&#xD;
Cordialement,&lt;br&gt;&#xD;
Philippe Royant&lt;br&gt;&#xD;
&lt;br&gt;&#xD;
&lt;br&gt;&#xD;
Hello,&lt;br&gt;&#xD;
I'm currently out of office. Back on Monday the 10th of August 2015.&lt;br&gt;&#xD;
&lt;br&gt;&#xD;
Best Regards,&lt;br&gt;&#xD;
Philippe Royant&lt;/p&gt;&#xD;
&lt;/div&gt;&#xD;
&lt;/div&gt;</t:Message></t:ReplyBody><t:Duration><t:StartTime>2015-07-22T14:30:00Z</t:StartTime><t:EndTime>2015-08-10T07:00:00Z</t:EndTime></t:Duration></t:OutOfOffice></m:MailTips></MailTipsResponseMessageType></ResponseMessages></GetMailTipsResponse></s:Body></s:Envelope>
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------

Good luck!


Regards,





import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;

public class OutOfOffice {

	public static void main(String[] args) throws Exception {

		

		URL url = new URL("ewsurl");
		HttpURLConnection rc = (HttpURLConnection) url.openConnection();

		rc.setRequestMethod("POST");
		rc.setDoOutput(true);
		rc.setDoInput(true);
		rc.setRequestProperty("Content-Type", "text/xml; charset=utf-8");

		String reqStr = 
			"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
			+ " xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			+ "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" "
			+ "xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\"><soap:Header>"
			+ " <t:RequestServerVersion Version=\"Exchange2010\"/></soap:Header><soap:Body>"
			+ "<GetMailTips xmlns=\"http://schemas.microsoft.com/exchange/services/2006/messages\">"
			+ "<SendingAs>"
			+ "<t:EmailAddress>mail1@co.fr</t:EmailAddress>"
			+ "<t:RoutingType>SMTP</t:RoutingType></SendingAs>"
			+ "<Recipients><t:Mailbox>"
			+ "<t:EmailAddress>philippe.royant@co.fr</t:EmailAddress>"
			+ "<t:RoutingType>SMTP</t:RoutingType></t:Mailbox></Recipients>"
			+ "<MailTipsRequested>OutOfOfficeMessage</MailTipsRequested></GetMailTips>"
			+ "</soap:Body></soap:Envelope>";

		int len = reqStr.length();
		//rc.setRequestProperty("SOAPAction:", "\"document/http://someurl.com/OfflineBatchSync/Order:CreateOrderHeader\"");
		rc.setRequestProperty("Content-Length", Integer.toString(len));
		rc.setRequestProperty("Connection:", "Keep-Alive");
		rc.connect();

		OutputStreamWriter outStr = new OutputStreamWriter(rc.getOutputStream());
		outStr.write(reqStr, 0, len);
		outStr.flush();

		InputStreamReader read;

		try {
			read = new InputStreamReader(rc.getInputStream());
		} catch (Exception exception) { 
			read = new InputStreamReader(rc.getErrorStream());
		}

		// read server response
		StringBuilder sb = new StringBuilder();
		int ch = read.read();
		while (ch != -1) {
			sb.append((char) ch);
			ch = read.read();
		}

		String responseTr = sb.toString();
		
		System.out.println(responseTr);
		
		//  http://blogs.msdn.com/b/devmsg/archive/2014/06/03/ews-how-to-retrieve-the-oof-out-of-facility-settings-message-using-ews-for-an-exchange-user.aspx

	}

}
