### ISSUE TITLE
Invoking EWS API in multi-threaded environment

### ISSUE THREAD

**Issue by choonchernlim** [OfficeDev/ews-java-api#370]
Is it possible to leverage the current EWS API in multi-threaded environment?

When querying the shared calendar based on given date range, it may or may not be slow depending on the date range size.

So, I split the date range into smaller ranges, then used `RxJava` where each thread invokes EWS API to process each small chunk... finally, combine them and return the data back to the caller.

I tried 2 approaches, but couldn't get both working. By the way, I'm using just one credential (a generic account) to connect to Exchange server.

My first approach is to create `ExchangeService` object, do stuff and then invoke `ExchangeService.close()` at the end of each thread... and I get this exception from one of the threads:-

	Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. 40
		at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
		at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
		at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:500)
		at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:519)
		at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:60)
		at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:75)
		at myproject.module.pto.service.impl.MicrosoftExchangeServiceImpl.query(MicrosoftExchangeServiceImpl.java:78)
		... 6 more
	Caused by: java.lang.ArrayIndexOutOfBoundsException: 40
		at org.apache.http.impl.auth.NTLMEngineImpl$NTLMMessage.addByte(NTLMEngineImpl.java:911)
		at org.apache.http.impl.auth.NTLMEngineImpl$NTLMMessage.addULong(NTLMEngineImpl.java:940)
		at org.apache.http.impl.auth.NTLMEngineImpl$Type1Message.getResponse(NTLMEngineImpl.java:1043)
		at org.apache.http.impl.auth.NTLMEngineImpl.getType1Message(NTLMEngineImpl.java:148)
		at org.apache.http.impl.auth.NTLMEngineImpl.generateType1Msg(NTLMEngineImpl.java:1628)
		at org.apache.http.impl.auth.NTLMScheme.authenticate(NTLMScheme.java:139)
		at org.apache.http.impl.auth.AuthSchemeBase.authenticate(AuthSchemeBase.java:138)
		at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:239)
		at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:202)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:262)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
		at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
		at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
		at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292)
		at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:720)
		at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
		at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	
My second approach is to create `ExchangeService` object as singleton where each thread can use it... but I get this error instead:-
	
	The request failed. Connection is still allocated
	
My goal is to be able to pull the shared calendar info fast enough to be displayed on the web at real time, and to ensure concurrent users try to perform the same query at the same time (using the same generic account) successfully.

What should I change to get this to work?

Thank you.

**Comment by evpaassen** [comment]
The `ExchangeService` class is by no means thread-safe. So you'll have to use one instance per thread. The `ArrayIndexOutOfBoundsException` could very well be a bug. Perhaps someone else have a look at this?

BTW, why is this issue closed? Did you solve it? If so, could you post your solution for future reference?

**Comment by serious6** [comment]
The `ArrayIndexOutOfBoundsException` fits when two threads will try to manipulate the byte[] in `NTLMEngineImpl`
