### ISSUE TITLE
 Bug in listing email using Microsoft Exchange Online 

### ISSUE THREAD

**Issue by cloudcomputingexperts** [OfficeDev/ews-java-api#378]
I am getting the below Exception while I am trying to list Microsoft Exchange-based email by connecting to our Office 365 Online Exchange email account using Outlook Web App. We are using this library to access Microsoft Exchange Online Service. 

<code>
! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3029670]
! Message: Connection reset
! at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596) ~[na:1.7.0_75]
! at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83) ~[na:1.7.0_75]
! at microsoft.exchange.webservices.data.core.EwsXmlReader.read(EwsXmlReader.java:201) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.EwsXmlReader.read(EwsXmlReader.java:182) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.EwsXmlReader.readValue(EwsXmlReader.java:467) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.EwsXmlReader.readValue(EwsXmlReader.java:436) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.EwsXmlReader.readElementValue(EwsXmlReader.java:359) ~[classes/:na]
! at microsoft.exchange.webservices.data.property.definition.TypedPropertyDefinition.loadPropertyValueFromXml(TypedPropertyDefinition.java:133) ~[classes/:na]
! at microsoft.exchange.webservices.data.property.definition.StringPropertyDefinition.loadPropertyValueFromXml(StringPropertyDefinition.java:34) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.PropertyBag.loadFromXml(PropertyBag.java:510) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.service.ServiceObject.loadFromXml(ServiceObject.java:298) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.response.FindItemResponse.internalReadItemsFromXml(FindItemResponse.java:185) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.response.FindItemResponse.readElementsFromXml(FindItemResponse.java:114) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.response.ServiceResponse.loadFromXml(ServiceResponse.java:133) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:76) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:44) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:433) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:401) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:63) ~[classes/:na]
! Causing: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[1,3029670]
! Message: Connection reset
! at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:981) ~[classes/:na]
! at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:1045) ~[classes/:na]
</code>

**Comment by serious6** [comment]
any more information if this error occurs trying to parse large data or is it just random?

**Comment by cloudcomputingexperts** [comment]
It's just a random data. My understanding is that server could not stay connected for long time so we are forcefully disconnecting/closing the Exchange Service/Server after the each `find item` request and then re-create the Exchange Service object. To fix the issue I have set page size to 10.  FYI: My inbox has 1500 email so when I am trying to list email of inbox with default page size 1000 it throws the above exception. If I set page size to 50 then it throws java.net.SocketException: Connection reset after 362 mails and if I set page size to just 10 then it throws  "java.net.SocketTimeoutException: Read timed out" after 1100 emails.  

<code>
 public void connect(){
        if(service==null) {
            System.setProperty("javax.net.debug", "ssl");
            service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
            ExchangeCredentials credentials = new WebCredentials(getProperties().get(USER),
                    CipherUtil.decrypt(getProperties().get(PASSWORD)));
            service.setCredentials(credentials);
            service.setTraceEnabled(true);
            try {
                service.setUrl(new URI("https://" + informationStoreDefinition.getProperties().get(DOMAIN) + "/ews/exchange.asmx"));
            } catch (Exception e) {
                throw new Exception("Could not connect to Exchange Online");
            }
            service.setPreAuthenticate(true);
            service.setTimeout(10*60*1000);
        }
    }
</code>

<code>
    public void disconnect(){
        if(service!=null)
        service.close();
        service=null;
    }
</code>

**Comment by Beelal** [comment]
+1 for fix.

**Comment by sg-garg** [comment]
I also faced the same issue.
