### ISSUE TITLE
Unparseable date pulling meeting from a calendar

### ISSUE THREAD

**Issue by brianskrab** [OfficeDev/ews-java-api#430]
Hello and thank you for you for maintaining this library.  It has proven far superior to the WSDL-based implementation I've been using.  I'm not certain how to reproduce this issue I'm seeing for a test case, but I'm getting an unparseable date error when requesting some items from a Calendar.

```
Caused by: java.text.ParseException: Unparseable date: "02:00:00"
        at java.text.DateFormat.parse(DateFormat.java:357)
        at microsoft.exchange.webservices.data.property.complex.TimeChange.tryReadElementFromXml(TimeChange.java:228)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.internalLoadFromXml(ComplexProperty.java:260)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:211)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:311)
        at microsoft.exchange.webservices.data.property.complex.MeetingTimeZone.tryReadElementFromXml(MeetingTimeZone.java:114)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.internalLoadFromXml(ComplexProperty.java:260)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:211)
        at microsoft.exchange.webservices.data.property.complex.ComplexProperty.loadFromXml(ComplexProperty.java:311)
        at microsoft.exchange.webservices.data.property.definition.MeetingTimeZonePropertyDefinition.loadPropertyValueFromXml(MeetingTimeZonePropertyDefinition.java:65)
        at microsoft.exchange.webservices.data.core.PropertyBag.loadFromXml(PropertyBag.java:510)
        at microsoft.exchange.webservices.data.core.service.ServiceObject.loadFromXml(ServiceObject.java:298)
        at microsoft.exchange.webservices.data.core.EwsServiceXmlReader.readServiceObjectsCollectionFromXml(EwsServiceXmlReader.java:169)
        at microsoft.exchange.webservices.data.core.response.GetItemResponse.readElementsFromXml(GetItemResponse.java:77)
        at microsoft.exchange.webservices.data.core.response.ServiceResponse.loadFromXml(ServiceResponse.java:133)
        at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:76)
        at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.parseResponse(MultiResponseServiceRequest.java:44)
        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:433)
        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:401)
        at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:63)
        ... 39 more
```

Looking at the code that does the parsing (TimeChange.tryReadElementFromXml()), I wonder if the final else if() statement should be using a different date format for Time elements.

```
  /**
   * Tries to read element from XML.
   *
   * @param reader accepts EwsServiceXmlReader
   * @return True if element was read
   * @throws Exception throws Exception
   */
  @Override
  public boolean tryReadElementFromXml(EwsServiceXmlReader reader)
      throws Exception {

    if (reader.getLocalName().equalsIgnoreCase(XmlElementNames.Offset)) {
      this.offset = EwsUtilities.getXSDurationToTimeSpan(reader.readElementValue());
      return true;
    } else if (reader.getLocalName().equalsIgnoreCase(
        XmlElementNames.RelativeYearlyRecurrence)) {
      this.recurrence = new TimeChangeRecurrence();
      this.recurrence.loadFromXml(reader, reader.getLocalName());
      return true;
    } else if (reader.getLocalName().equalsIgnoreCase(
        XmlElementNames.AbsoluteDate)) {
      SimpleDateFormat sdfin = new SimpleDateFormat(
          "yyyy-MM-dd'T'HH:mm:ss");
      Date tempDate = sdfin.parse(reader.readElementValue());
      this.absoluteDate = tempDate;
      return true;
    } else if (reader.getLocalName().equalsIgnoreCase(XmlElementNames.Time)) {
      SimpleDateFormat sdfin = new SimpleDateFormat(
          "yyyy-MM-dd'T'HH:mm:ss");
      Date tempDate = sdfin.parse(reader.readElementValue());
      this.time = new Time(tempDate);
      return true;
    } else {
      return false;
    }
  }
```

Is there something else I'm missing?

I look forward to any feedback you can provide regarding this error.

Thank you!

~brian

**Comment by itbw** [comment]
@brianskrab I had the similar problem. I created a PR #420 recently and wait for evaluation

**Comment by serious6** [comment]
@brianskrab @itbw PR has been merged can you confirm this issue to be fixed? If not please reopen.
