### ISSUE TITLE
Error when calling load() on an EmailMessage item

### ISSUE THREAD

**Issue by bah7303** [OfficeDev/ews-java-api#440]
I am getting an error loading an EmailMessage that contains a character string that will not parse as xml. Is there some specific work around for this?  

This might be addressed by the changes in the following link but I was not sure how to make use of it:
https://github.com/OfficeDev/ews-java-api/pull/409/files#r37471388

Error when calling load() on an EmailMessage item:
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[51,6]
Message: Character reference "&#

**Comment by serious6** [comment]
Ref. #353

**Comment by bah7303** [comment]
Was this fix included in the 2.0 release? I am not seeing it in EwsUtilities.class?  Am I missing something, any help would be greatly appreciated.

**Comment by serious6** [comment]
no, the original issue is still open. We have a pending PR for this with another 3rd party dependency which we try to get rid of.

**Comment by sg-garg** [comment]
I am also facing the same issue while calling item.load()

Exception in thread "main" microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[9,2543]
Message: Character reference "&#
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalLoadPropertiesForItems(ExchangeService.java:1324)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalLoad(Item.java:193)
	at microsoft.exchange.webservices.data.core.service.ServiceObject.load(ServiceObject.java:384)
	at cots.sg.test.EWSBBEmailServices.readAndParseEmails(EWSBBEmailServices.java:163)
	at cots.sg.test.EWSBBEmailServices.main(EWSBBEmailServices.java:219)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[9,2543]
Message: Character reference "&#

**Comment by blackfrancis** [comment]
I don't understand how the EWS api is useable at all with this bug open.

**Comment by wsat** [comment]
Just got the same error. Any news?
