### ISSUE TITLE
ClassNotFoundException - ExchangeCredentials

### ISSUE THREAD

**Issue by selvait90** [OfficeDev/ews-java-api#449]
I have imported ews-java-api library and tried to send a message. But I have no idea why it is complaining class not found error on ExchangeCredentials. I have rebuilt the library from source but it doesn't help to fix the problem. Can anyone please help me on this ?

## Code
```java
package com.company.util;

import microsoft.exchange.webservices.data.core.ExchangeService;
import microsoft.exchange.webservices.data.core.enumeration.misc.ExchangeVersion;
import microsoft.exchange.webservices.data.core.service.item.EmailMessage;
import microsoft.exchange.webservices.data.credential.ExchangeCredentials;
import microsoft.exchange.webservices.data.credential.WebCredentials;
import microsoft.exchange.webservices.data.property.complex.MessageBody;

import java.net.URI;
import java.net.URISyntaxException;

/**
 * Created by selva on 21/10/15.
 */
public class EWSConnection {

    private static String defaultServer = "outlook.office365.com";
    private static String serverUrl = "https://outlook.office365.com/EWS/Exchange.asmx";

    public void sendMessage() {
        ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
        ExchangeCredentials credentials = new WebCredentials("test1@test.org", "testpasword");
        service.setCredentials(credentials);
        try {
            service.setUrl(new URI(serverUrl));
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        try {
            EmailMessage msg = new EmailMessage(service);
            msg.setSubject("Hello world!");
            msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Java API."));
            msg.getToRecipients().add("selva@company.com");
            msg.send();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

## Error Stack
```java
Exception in thread "pool-5-thread-1" java.lang.NoClassDefFoundError: microsoft/exchange/webservices/data/credential/ExchangeCredentials
        at com.company.util.EmailBuilder.com$company$util$EmailBuilder$$sendImpl(EmailBuilder.scala:232)
        at com.company.util.EmailBuilder$$anon$3.run(EmailBuilder.scala:254)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: microsoft.exchange.webservices.data.credential.ExchangeCredentials
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
        ... 5 more
```

**Comment by selvait90** [comment]
I found the root cause. The entire application was complied successfully. The exception comes up only at run time and I missed to add ews-java-api library to Jetty server class path. Also I have faced few other run time dependencies and resolved by adding recent version of couple of libraries. Thanks
