### ISSUE TITLE
Error PKIX path building failed 

### ISSUE THREAD

**Issue by andrespineda23** [OfficeDev/ews-java-api#468]
Hi. i'm triying send a appointment but i have the next error :/ help me please 

I hava installed Cert_Outlook

```Exception
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:174)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1623)
	at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:198)
	at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:192)
	at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1074)
	at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:128)
	at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:529)
	at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:465)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:884)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1120)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:623)
	at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at microsoft.exchange.webservices.data.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:300)
	at microsoft.exchange.webservices.data.ServiceRequestBase.emit(ServiceRequestBase.java:326)
	at microsoft.exchange.webservices.data.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:714)
	... 8 more
```

**Comment by serious6** [comment]
Have you already tried [customizing the service](https://github.com/OfficeDev/ews-java-api/wiki/Custom-Exchange-services)?

**Comment by serious6** [comment]
ref #57
