### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by senneko** [OfficeDev/ews-java-api#475]
Hi. I’ve the next issue: 
The request failed. The remote server returned an error: (401) Unauthorized.

I’m trying to send an appointment but when the process ends (appointment.save()) I have this problem.

I'm trying to connect the service as follows:

            ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
            ExchangeCredentials credentials =  WebCredentials(user, pass, domain);
            service.setCredentials(credentials);
            service.setUrl(new URI("https://XXXXXXX/ews/exchange.asmx"));

Somebody knows how to fix it? Thanks.

**Comment by serious6** [comment]
try connecting with the same credentials and url using the [ews-editor](https://ewseditor.codeplex.com/)

**Comment by senneko** [comment]
I have one problem. The program is in an environment where only the administrator has access. Therefore I can not perform the test with the tool mentioned.

Is there any other way to solve this problem locally?

**Comment by serious6** [comment]
The reason I suggested this tool is to check on your credentials or the provided URL as the error you reported might have its origin there. This API is about requests and responses to an exchange Server so if you dont have your exchange Server configured locally there is nothing to test with. Maybe provide some additional information about your environment.

**Comment by avromf** [comment]
To test general connectivity issues to an Exchange Server you can also try this:
https://testconnectivity.microsoft.com/
Select "Service Account Access (Developers)" under "Microsoft Exchange Web Services Connectivity Tests".

**Comment by senneko** [comment]
I found the problem. the domain that was using was wrong. I change the domain and effectively the problem of authorization was eliminated.
Thank you for your help.

**Comment by amolthorat1991** [comment]
Hi,
I tried to connect to exchange mail server using the ews service provided but I am getting the following issue. Can you please help me on this..

microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (401)Unauthorized
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
	at mailservice.MSExchangeEmailService.main(MSExchangeEmailService.java:211)
Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The remote server returned an error: (401)Unauthorized
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:651)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	... 7 more
Caused by: microsoft.exchange.webservices.data.core.exception.http.HttpErrorException: The remote server returned an error: (401)Unauthorized
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:725)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:646)
	... 8 more

**Comment by bss-damini-yadav** [comment]
Do you have a solution?
For this- >The request failed. The remote server returned an error: (401).
