### ISSUE TITLE
Error sending mail via EWS Exchange for Android : java.lang.NullPointerException: format == null

### ISSUE THREAD

**Issue by thejaswi28** [OfficeDev/ews-java-api#494]
Hi,

Below is my code I am using to send mail using EWS for Android. 

EmailMessage msg= new EmailMessage(service);
                msg.setSubject("Hello world!");
                msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Java API."));
                msg.getToRecipients().add("myemail");
                msg.send();

However it is not working and I am getting the below error. Can anybody please tell me about this.

02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ java.lang.NullPointerException: format == null
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.lang.String.format(String.java:1799)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.lang.String.format(String.java:1777)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:936)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:821)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:46)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:143)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.ExchangeService.internalCreateItems(ExchangeService.java:463)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.ExchangeService.createItem(ExchangeService.java:534)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.Item.internalCreate(Item.java:215)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.EmailMessage.internalSend(EmailMessage.java:125)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at microsoft.exchange.webservices.data.EmailMessage.send(EmailMessage.java:253)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at com.example.test.MainActivity$EWSOperation.doInBackground(MainActivity.java:61)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at com.example.test.MainActivity$EWSOperation.doInBackground(MainActivity.java:39)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:292)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-12 03:26:00.411  18432-18457/com.example.test W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

**Comment by aqibmapari** [comment]
I think you need to update your Jar file to the latest version.

I was facing this issue when using a 2 year old jar file.
Just update my jar file and got past this.

**Comment by serious6** [comment]
Also including a build manager as maven or gradle is highly recommended ;-)
