### ISSUE TITLE
Can not send email to a personal contact : "Cannot use personal contacts as recipients or attendees."

### ISSUE THREAD

**Issue by sxilderik** [OfficeDev/ews-java-api#512]
Hello

If I add a recipient to and email with the same email address as one of my personal contacts, I get this exception on using sendAndSaveCopy :

> 14:13:50,550 microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: Cannot use personal contacts as recipients or attendees.
14:13:50,551 	at microsoft.exchange.webservices.data.core.response.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:278)
14:13:50,552 	at microsoft.exchange.webservices.data.core.response.ServiceResponse.throwIfNecessary(ServiceResponse.java:267)
14:13:50,553 	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:165)
14:13:50,554 	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
14:13:50,556 	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
14:13:50,557 	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
14:13:50,558 	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
14:13:50,560 	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.sendAndSaveCopy(EmailMessage.java:300)

This is probably related to this issue : https://github.com/OfficeDev/ews-managed-api/issues/69

Is there a workaround, or a solution ?

Thanks !

**Comment by sxilderik** [comment]
I also get the same error trying to save an appointment with attendees of which one address is the same as one of my personal contacts, this time on Appointment.save()

> 14:35:12,309 microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: Cannot use personal contacts as recipients or attendees.
14:35:12,310 	at microsoft.exchange.webservices.data.core.response.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:278)
14:35:12,311 	at microsoft.exchange.webservices.data.core.response.ServiceResponse.throwIfNecessary(ServiceResponse.java:267)
14:35:12,312 	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:165)
14:35:12,314 	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
14:35:12,315 	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
14:35:12,316 	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
14:35:12,317 	at microsoft.exchange.webservices.data.core.service.item.Appointment.save(Appointment.java:392)

**Comment by sxilderik** [comment]
**Solved**

Before using an adress, I try to "resolve" it. If the resolution is that of a personal contact, the mailBox object holds a _non-null itemId_. By nulling it before using that EmailAddress as a recipient or attendee, the problem no longer occurs.
