### ISSUE TITLE
ServiceRequestBase.readResponse() NullPointerException

### ISSUE THREAD

**Issue by philci52** [OfficeDev/ews-java-api#567]
Stacktrace below,  The issue is that HttpWebRequest.getContentEncoding() can return null, but null is not checked for in ServiceRequestBase.readResponse():369

`Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:505)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:523)
	at microsoft.exchange.webservices.data.core.service.folder.Folder.bind(Folder.java:98)
	at microsoft.exchange.webservices.data.core.service.folder.Folder.bind(Folder.java:147)
	... 9 more
Caused by: java.lang.NullPointerException
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.readResponse(ServiceRequestBase.java:369)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:63)`

**Comment by Intelligent2013** [comment]
I've had the same issue. I use rackspace exchange email service and when I set recomended URL https://mex09.emailsrvr.com, then I get above exception.
**302** is response code and it means that response body contains a redirection (new) location, but looks like that this library doesn't support redirection. Therefore you have to set URL in code to URL from location value. But in my case it didn't help me and I get error 440 (login timeout). (But in any case the correct URL for rackspace is https://mex09.emailsrvr.com/EWS/Exchange.asmx)

**Comment by yw411** [comment]
@Intelligent2013 ,I meet the same error 440(login timeout).Did you solve the error?

**Comment by Intelligent2013** [comment]
@yw411  Yes, I've solved this issue by using URL https://mex09.emailsrvr.com/EWS/Exchange.asmx instead of recommended https://mex09.emailsrvr.com (I've used rackspace email service). In your case try to use more concrete URL (with .asmx on the end).

**Comment by yw411** [comment]
@Intelligent2013 ,I have tried the url but still error 440. I think maybe the exchange server's configuration is not correct, so if there are something  that I have to pay attention to (for example: authentication)

**Comment by philci52** [comment]
Even if people solve this by using a different URL, the library should not generate NPE if XML is not returned.
