### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by mallikarjundontamsetti** [OfficeDev/ews-java-api#57]
Am getting following error while Could you please help on this.

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
    at sun.security.validator.Validator.validate(Validator.java:260)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
    at microsoft.exchange.webservices.data.EwsX509TrustManager.checkServerTrusted(EwsX509TrustManager.java:62)
    at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:865)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)

**Comment by dotCipher** [comment]
:+1: It would potentially be really slick if we could build and pass in our own `EwsSSLProtocolSocketFactory` into the `ExchangeService`.  This would allow one to not need to install the cert onto the local machine's `cacerts` and instead package a specific truststore that could be passed in a limited scope to the `ExchangeService`, thus averting the need to set the jvm system properties as well.

**Comment by ggeorgovassilis** [comment]
+1 on specifying custom connection providers. Importing certificates in the global JVM keystore isn't always possible, e.g. I don't control the JVM or application server the application is running on or the application runs in a managed environment like cloud foundry.
