### ISSUE TITLE
[2.0] testOlsonTimeZoneConversion fails

### ISSUE THREAD

**Issue by OzoneGrif** [OfficeDev/ews-java-api#571]
This is from tag release-2.0, when I run Maven install, one of the test fails:

```
testOlsonTimeZoneConversion(microsoft.exchange.webservices.data.property.complex.OlsonTimeZoneTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at microsoft.exchange.webservices.data.property.complex.OlsonTimeZoneTest.testOlsonTimeZoneConversion(OlsonTimeZoneTest.java:57)
```
It did the same thing last week on another computer, and all tests passed...

Both computers are Win10, in English, with a timezone UTC +01:00 Brussels, Copenhagen, Madrid, Paris

**Comment by mredz** [comment]
Yes I have this exception also.
