### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/protocol/HttpClientContext;

### ISSUE THREAD

**Issue by PieterMobile** [OfficeDev/ews-java-api#574]
I tried to MS Exchange async with this api.

useLibrary 'org.apache.http.legacy' in my graddle file

dependencies {
    ...
    compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'
    compile ('com.microsoft.ews-java-api:ews-java-api:2.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    ...
}

btw, it occurs error as follows when i login to our Exchange server with my account

Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes3.dex)
                      at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
                      at microsoft.exchange.webservices.data.core.ExchangeServiceBase.createConnectionSocketFactoryRegistry(ExchangeServiceBase.java:244)
                      at microsoft.exchange.webservices.data.core.ExchangeServiceBase.initializeHttpClient(ExchangeServiceBase.java:198)
                      at microsoft.exchange.webservices.data.core.ExchangeServiceBase.<init>(ExchangeServiceBase.java:174)
                      at microsoft.exchange.webservices.data.core.ExchangeServiceBase.<init>(ExchangeServiceBase.java:179)
                      at microsoft.exchange.webservices.data.core.ExchangeService.<init>(ExchangeService.java:3729)
                      at 

Any idea how to solve this issue?

**Comment by PieterMobile** [comment]
Just solved that issue by add "compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'" to gradle dependencies.

**Comment by gaby44541** [comment]
Decompile the class org/apache/http/conn/ssl/AllowAllHostnameVerifier and look if you have the field INSTANCE. 
If no, use another version of the dependancy.
If yes, your application use an another version of the dependancy. I had the same problem, and weblogic use a lower version of a dependancy i had whereas i had a upper version.

**Comment by PieterMobile** [comment]
Thanks gaby44541!
which one is another version of the dependancy that you noticed? (httpclient or ews-java-api)

**Comment by gaby44541** [comment]
For me it was org.joda. For you, probably httpclient. 
Look here, https://github.com/OfficeDev/ews-java-api/issues/492
Perhaps it will help you.

**Comment by serious6** [comment]
_closed until other indication by reporter_
