### ISSUE TITLE
Call EWS from a Web-Service

### ISSUE THREAD

**Issue by gaby44541** [OfficeDev/ews-java-api#582]
Hi,
When i call the API from a web service, i have an error.
Here is the full stacktrace.
FYI, com.ixbat.synchroexchangews is our web-service. It calls a jar (synchroexchange.*), which call the API EWS.

> microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
	at microsoft.exchange.webservices.data.core.service.item.Item.save(Item.java:386)
	at synchroexchange.ExtendedTask.create(ExtendedTask.java:108)
	at synchroexchange.ExchangeManager.wsPropagerAction(ExchangeManager.java:734)
	at synchroexchange.ExchangeManager.wsPropagerAction(ExchangeManager.java:702)
	at com.ixbat.synchroexchangews.SynchroExchangews.propagerAction(SynchroExchangews.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:117)
	at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:91)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:149)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:88)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:419)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:868)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:422)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:169)
	at weblogic.wsee.jaxws.WLSServletAdapter.handle(WLSServletAdapter.java:199)
	at weblogic.wsee.jaxws.HttpServletAdapter$AuthorizedInvoke.run(HttpServletAdapter.java:640)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)
	at weblogic.wsee.util.ServerSecurityHelper.authenticatedInvoke(ServerSecurityHelper.java:108)
	at weblogic.wsee.jaxws.HttpServletAdapter$3.run(HttpServletAdapter.java:284)
	at weblogic.wsee.jaxws.HttpServletAdapter.post(HttpServletAdapter.java:293)
	at weblogic.wsee.jaxws.JAXWSServlet.doRequest(JAXWSServlet.java:128)
	at weblogic.servlet.http.AbstractAsyncServlet.service(AbstractAsyncServlet.java:99)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at oracle.security.jps.ee.http.JpsAbsFilter$1.run(JpsAbsFilter.java:137)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.security.jps.util.JpsSubject.doAsPrivileged(JpsSubject.java:315)
	at oracle.security.jps.ee.util.JpsPlatformUtil.runJaasMode(JpsPlatformUtil.java:460)
	at oracle.security.jps.ee.http.JpsAbsFilter.runJaasMode(JpsAbsFilter.java:120)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilter(JpsAbsFilter.java:217)
	at oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:81)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:220)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3436)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
Caused by: java.lang.NullPointerException
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:451)
	at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.writeValue(EwsServiceXmlWriter.java:307)
	at microsoft.exchange.webservices.data.property.complex.StringList.writeElementsToXml(StringList.java:117)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.writeToXml(ComplexProperty.java:325)
	at microsoft.exchange.webservices.data.property.complex.ComplexProperty.writeToXml(ComplexProperty.java:338)
	at microsoft.exchange.webservices.data.property.definition.ComplexPropertyDefinitionBase.writePropertyValueToXml(ComplexPropertyDefinitionBase.java:170)
	at microsoft.exchange.webservices.data.core.PropertyBag.writeToXml(PropertyBag.java:548)
	at microsoft.exchange.webservices.data.core.service.ServiceObject.writeToXml(ServiceObject.java:321)
	at microsoft.exchange.webservices.data.core.request.CreateRequest.writeElementsToXml(CreateRequest.java:129)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.writeBodyToXml(ServiceRequestBase.java:134)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.writeToXml(ServiceRequestBase.java:256)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:696)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:665)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	... 63 more

Thanks for your help

**Comment by gaby44541** [comment]
I found a solution of a very strange problem: 
I downloaded the project EWS Java API. I logged every step to find the problem. 
Result : it's in the class ComplexProperty, line 330 - [https://github.com/kaaaaang/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/ComplexProperty.java](https://github.com/kaaaaang/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/ComplexProperty.java).

The method : this.writeElementsToXml(writer) cause the exception. The very strange thing is this method is empty. If I remove this line, it works.

The problem is when i call EWS from a web-service.

Do you have any idea why this empty method cause a bug ?

There is one problem : the body of the task/calendar is not synchronized. The title/date/hour are synchronize.

Do you know why ?

Thanks

**Comment by gaby44541** [comment]
Ok, it's resolved. In fact, I putted null in the stringlist of the task categories : new StringList(cat), with cat == null.
If you have a problem like this, i advice you to read the fullstacktrace (here on the bottom it is written nullpointerexception in the stringList).
And the second advice is to download the project, write System.out.println and generate the jar.

**Comment by serious6** [comment]
_solved_
