### ISSUE TITLE
Error while reading mail using ews java api: Illegal character entity: expansion character (code 0x1)

### ISSUE THREAD

**Issue by amolthorat19** [OfficeDev/ews-java-api#590]
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. Illegal character entity: expansion character (code 0x1
 at [row,col {unknown-source}]: [1,2690]
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalBindToItems(ExchangeService.java:1343)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1378)
	at microsoft.exchange.webservices.data.core.ExchangeService.bindToItem(ExchangeService.java:1395)
	at microsoft.exchange.webservices.data.core.service.item.Item.bind(Item.java:121)

**Comment by amolthorat19** [comment]
Hi All, Please help how I can resolve this issue..

**Comment by gdoda** [comment]
@amolthorat19 did you manage to solve this issue? I have the same problem
