### ISSUE TITLE
send( ) ,microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null

### ISSUE THREAD

**Issue by yw411** [OfficeDev/ews-java-api#611]
when i call the function send( ) ,i meet the following error:
`microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:151)
	at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
	at test.Exchange.sendMessage(Exchange.java:162)
	at test.Exchange.main(Exchange.java:191)
Caused by: java.lang.NullPointerException
	at microsoft.exchange.webservices.data.core.ExchangeServiceBase.prepareHttpWebRequestForUrl(ExchangeServiceBase.java:319)
	at microsoft.exchange.webservices.data.core.ExchangeService.prepareHttpWebRequest(ExchangeService.java:3748)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:664)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	... 8 more`

**Comment by antsarandriamihaja** [comment]
@yw411 I am having a similar issue. Did you solve this?

**Comment by yw411** [comment]
@antsarandriamihaja ，I remember I wrote a url  whose position is  **( ExchangeService.setUrl(url))** wrong
