### ISSUE TITLE
Auth scheme is null

### ISSUE THREAD

**Issue by OS-JaR** [OfficeDev/ews-java-api#614]
Hi,
I'm currently getting this Exception when binding to an EmailMessage. I'm pretty sure this isn't any configuration problem, cause generally it's working. My application is running multiple threads to bind items and process them. Does anyone had this problem before?
 Stacktrace:

`Caused by: java.lang.IllegalStateException: Auth scheme is null
	at org.apache.http.util.Asserts.notNull(Asserts.java:52)
	at org.apache.http.impl.auth.HttpAuthenticator.ensureAuthScheme(HttpAuthenticator.java:229)
	at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:184)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:262)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:722)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:646)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	... 51 more
`

**Comment by rsjssc** [comment]
hi, i face the same problem, do anyone has any solutions ?

**Comment by pdavie** [comment]
I resolved this issue by ensuring my project was using v4.4.1 of Apache httpclient, i.e. with maven:
```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.4.1</version>
</dependency>
```
