### ISSUE TITLE
Premature end of file

### ISSUE THREAD

**Issue by min-ye-tfs** [OfficeDev/ews-java-api#708]
Hi,
I want to download attachment from email message,but sometimes it can be throw exception like
`microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[1,868391]
Message: Premature end of file.
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalGetAttachments(ExchangeService.java:1503)
	at microsoft.exchange.webservices.data.core.ExchangeService.getAttachment(ExchangeService.java:1538)
	at microsoft.exchange.webservices.data.property.complex.Attachment.internalLoad(Attachment.java:411)
	at microsoft.exchange.webservices.data.property.complex.Attachment.load(Attachment.java:430)
	at microsoft.exchange.webservices.data.property.complex.FileAttachment.load(FileAttachment.java:234)`

**Comment by leungyukshing** [comment]
Same problem. Anyone fix this?

**Comment by matrenner** [comment]
same issue. get this error intermittently
