### ISSUE TITLE
How to trust SSL certificate?

### ISSUE THREAD

**Issue by bvn13** [OfficeDev/ews-java-api#715]
Our Exchange Server is hosted on domain with self-signed certificate therefore I have this exception:
```
Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:729) ~[ews-java-api-2.0.jar:na]
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639) ~[ews-java-api-2.0.jar:na]
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62) ~[ews-java-api-2.0.jar:na]
	... 18 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[na:1.8.0_222]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_222]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar:4.5.10]
	at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292) ~[ews-java-api-2.0.jar:na]
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:720) ~[ews-java-api-2.0.jar:na]
	... 20 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[na:1.8.0_222]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_222]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237) ~[na:1.8.0_222]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113) ~[na:1.8.0_222]
	at microsoft.exchange.webservices.data.core.EwsX509TrustManager.checkServerTrusted(EwsX509TrustManager.java:83) ~[ews-java-api-2.0.jar:na]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1099) ~[na:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[na:1.8.0_222]
	... 40 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_222]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_222]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_222]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_222]
	... 48 common frames omitted
```

How to trust self-signed certificate?

**Comment by bvn13** [comment]
Ok. I found a solution creating TrustAllTrustManager. Will a PR be reviewed and accepted if I create it? Willn't it be a your policy violation?

**Comment by rashad-farajullayev** [comment]
How do we trust server's self signed certificate? 
We are currently having this issue.

**Comment by chris-metz** [comment]
Same problem here, internal Exchange with self signed cert. @bvn13 Would be interested how you solved this if you dont't mind sharing.

**Comment by davidmoten** [comment]
This can be solved outside of this library I think. All you need to do is add the self-signed certificate to the trust store of the jre being used by the client.

https://docs.oracle.com/cd/E76310_01/pdf/1411/html/merch_sg/apps-chapter%207.htm#CHDJBIJD

**Comment by davidmoten** [comment]
By the way if you don't want to change the jre truststore you can also do this sort of thing locally in a webapp by modifying the SSLContext to use a truststore from the classpath (optionally extending the default truststore from the jre). Let me know if you need the code.

**Comment by dvgaba** [comment]
We are using system property to set trust-store and key-store.
-Djavax.net.ssl.truststore=FILE_PATH_TS
-Djavax.net.ssl.keystore=FILE_PATH_KS

and corresponding passwords

**Comment by thesohelshaikh** [comment]
I am trying to trust a self signed certificate from exchange server.
I have created a custom class that extends ExchangeSession that uses EwsSSLFactory and overrides the default http client. I'll share the snippet bellow. I don't think exchange is using my TrustManager. Since I am working on application where there will be multiple users, adding the cert to the lib is not an option. I want exchange to trust the certificates.
But when I try to get the inbox folder I get an exception. -
 W/System.err: Caused by: `microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`


```
public class ExchangeServiceInsecure extends ExchangeService {
    public ExchangeServiceInsecure() {
        initializeHttpClient();
    }
    public void initializeHttpClient() {
        try {
            TrustManager tm = new X509TrustManager() { // Trusts all certificates
                @Override
                public void checkClientTrusted(X509Certificate[] chain, String authType) {
                    Log.d("INSECURE", "checkClientTrusted: ");
                }
                @Override
                public void checkServerTrusted(X509Certificate[] chain, String authType) {
                    Log.d("INSECURE", "checkServerTrusted: ");
                }
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return new X509Certificate[0];
                }
            };
            EwsSSLProtocolSocketFactory sf = EwsSSLProtocolSocketFactory.build(
                    tm, NoopHostnameVerifier.INSTANCE);
            Registry<ConnectionSocketFactory> registry = RegistryBuilder.<ConnectionSocketFactory>create()
                    .register(EWSConstants.HTTP_SCHEME, new PlainConnectionSocketFactory())
                    .register(EWSConstants.HTTPS_SCHEME, sf)
                    .build();
            HttpClientConnectionManager httpConnectionManager = new PoolingHttpClientConnectionManager(registry);
            AuthenticationStrategy authStrategy = new CookieProcessingTargetAuthenticationStrategy();
            httpClient = HttpClients.custom()
                    .setConnectionManager(httpConnectionManager)
                    .setTargetAuthenticationStrategy(authStrategy)
                    .setSslcontext(sf.getContext())
                    .build();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by curious137** [comment]
I am trying to trust a self signed certificate from exchange server.

I have created a custom class that extends ExchangeService that uses EwsSSLFactory and overrides the default http client. I'll share the snippet bellow. I don't think exchange is using my TrustManager. 

Since I am working on application where there will be multiple users, adding the certificate to the lib is not an option. I want exchange to trust the certificates.

```
public class ExchangeServiceInsecure extends ExchangeService {
    public ExchangeServiceInsecure() {
        initializeHttpClient();
    }
    public void initializeHttpClient() {
        try {
            TrustManager tm = new X509TrustManager() { // Trusts all certificates
                @Override
                public void checkClientTrusted(X509Certificate[] chain, String authType) {

                }
                @Override
                public void checkServerTrusted(X509Certificate[] chain, String authType) {

                }
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return new X509Certificate[0];
                }
            };
            EwsSSLProtocolSocketFactory sf = EwsSSLProtocolSocketFactory.build(
                    tm, NoopHostnameVerifier.INSTANCE);
            Registry<ConnectionSocketFactory> registry = RegistryBuilder.<ConnectionSocketFactory>create()
                    .register(EWSConstants.HTTP_SCHEME, new PlainConnectionSocketFactory())
                    .register(EWSConstants.HTTPS_SCHEME, sf)
                    .build();
            HttpClientConnectionManager httpConnectionManager = new PoolingHttpClientConnectionManager(registry);
            AuthenticationStrategy authStrategy = new CookieProcessingTargetAuthenticationStrategy();
            httpClient = HttpClients.custom()
                    .setConnectionManager(httpConnectionManager)
                    .setTargetAuthenticationStrategy(authStrategy)
                    .setSslcontext(sf.getContext())
                    .build();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
But when I try to get the inbox folder I get an exception -

```
W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
W/System.err:     at android.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
W/System.err:     at android.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
W/System.err:     at android.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
W/System.err:     at android.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
W/System.err:     at android.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
W/System.err:     at android.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
W/System.err:     at android.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
W/System.err:     at android.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
W/System.err:     at android.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
W/System.err:     at android.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
W/System.err:     at android.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err:     at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:310)
W/System.err:     at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:722)
    	... 16 more
```

**Comment by peter-szrnka** [comment]
> By the way if you don't want to change the jre truststore you can also do this sort of thing locally in a webapp by modifying the SSLContext to use a truststore from the classpath (optionally extending the default truststore from the jre). Let me know if you need the code.

Could you provide a sample code how to do this?  Thanks in advance!

**Comment by davidmoten** [comment]
@szrnka-peter 

```java
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.security.KeyManagementException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.TrustManager;
import javax.net.ssl.TrustManagerFactory;
import javax.net.ssl.X509ExtendedTrustManager;
import javax.net.ssl.X509TrustManager;

public final class ExtendedTrustManager extends X509ExtendedTrustManager {

    private final X509TrustManager defaultTm;
    private final X509TrustManager customTm;

    public ExtendedTrustManager(InputStream trustStoreInputStream, char[] trustStorePassword) {
        try {
            X509TrustManager defaultTm = null;
            {
                TrustManagerFactory tmf = TrustManagerFactory
                        .getInstance(TrustManagerFactory.getDefaultAlgorithm());
                tmf.init((KeyStore) null);
                for (TrustManager tm : tmf.getTrustManagers()) {
                    if (tm instanceof X509TrustManager) {
                        defaultTm = (X509TrustManager) tm;
                        break;
                    }
                }
            }
            this.defaultTm = defaultTm;
            final KeyStore trustStore;
            trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
            trustStore.load(trustStoreInputStream, trustStorePassword);

            TrustManagerFactory tmf = TrustManagerFactory
                    .getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(trustStore);
            X509TrustManager customTm = null;
            for (TrustManager tm : tmf.getTrustManagers()) {
                if (tm instanceof X509TrustManager) {
                    customTm = (X509TrustManager) tm;
                    break;
                }
            }
            this.customTm = customTm;
        } catch (KeyStoreException | NoSuchAlgorithmException | CertificateException
                | IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType)
            throws CertificateException {
        defaultTm.checkClientTrusted(chain, authType);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType)
            throws CertificateException {
        try {
            customTm.checkServerTrusted(chain, authType);
        } catch (CertificateException e) {
            defaultTm.checkServerTrusted(chain, authType);
        }

    }

    @Override
    public final X509Certificate[] getAcceptedIssuers() {
        return defaultTm.getAcceptedIssuers();
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, Socket socket)
            throws CertificateException {
        checkClientTrusted(chain, authType);
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType, SSLEngine engine)
            throws CertificateException {
        checkClientTrusted(chain, authType);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, Socket socket)
            throws CertificateException {
        checkServerTrusted(chain, authType);
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType, SSLEngine engine)
            throws CertificateException {
        checkServerTrusted(chain, authType);
    }

    public static SSLContext createTlsContextWithExtendedTrustManager(InputStream trustStore,
            String trustStorePassword) throws NoSuchAlgorithmException, KeyManagementException {
        SSLContext sslContext = SSLContext.getInstance("TLS");
        TrustManager trustManager = new ExtendedTrustManager(trustStore,
                trustStorePassword.toCharArray());
        TrustManager[] trustManagers = new TrustManager[] { trustManager };
        sslContext.init(null, trustManagers, new java.security.SecureRandom());
        return sslContext;
    }

}
```
To use:

```java
String trustStorePassword = ...;
SSLContext context;
try (InputStream is = SomeClass.class.getResourceAsStream("/trustStore.jks")) {
    context = ExtendedTrustManager.createTlsContextWithExtendedTrustManager(is,
                    trustStorePassword);
}
SSLSocketFactory factory = context.getSocketFactory();
Socket socket = factory.createSocket(host, port);
socket.setKeepAlive(true);
socket.setSoTimeout(readTimeoutMs);
Reader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
```




```
